### ISSUE TITLE
Param toolbarColor of window ignored

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#522]
Param toolbarColor of window ignored in XML and in Java.

I use the purple theme if it can help reproduce.

I use the 2.0-rc3 version.

I got the same using the 2.0-SNAPSHOT version.

Hope it helps.

**Comment by kevzlou7979** [comment]
Ok I think there is  some !important attribute that is conflicted with the toolbarColor. WIll insvestigate it further

**Comment by kevzlou7979** [comment]
Fixed via - https://github.com/GwtMaterialDesign/gwt-material-themes/commit/ea4dcc2479ad2606bbbc26f4ed7a1b661540e63a

**Comment by reofake** [comment]
Sorry, but with that commit, now all windows are blue, and the toolbarColor param is still ignored.

**Comment by kevzlou7979** [comment]
Have you tried to update GMD Themes2.0-SNAPSHOT into your repo?

**Comment by reofake** [comment]
Yes, this is the pom.xml I use :
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>reofake-demo</artifactId>
    <groupId>reofake</groupId>
    <packaging>war</packaging>
    <version>1.0</version>

    <properties>
        <!-- client -->
        <gwt.version>2.8.0</gwt.version>
        <gwtp.version>1.5.3</gwtp.version>
        <gin.version>2.1.2</gin.version>
        <gwt.style>PRETTY</gwt.style>
        <gwt-material.ext>-SNAPSHOT</gwt-material.ext>
        <gwt-material.version>2.0${gwt-material.ext}</gwt-material.version>
        <gwt-material-table.version>1.0${gwt-material.ext}</gwt-material-table.version>

        <!-- maven -->
        <maven-compiler-plugin.version>3.6.0</maven-compiler-plugin.version>

        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.resourceEncoding>UTF-8</project.build.resourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <project.encoding>UTF-8</project.encoding>
        
        <maven.javadoc.skip>true</maven.javadoc.skip>
        
        <webappDirectory>${project.build.directory}/${project.build.finalName}</webappDirectory>
    </properties>
    
    <build>
        <outputDirectory>${webappDirectory}/WEB-INF/classes</outputDirectory>
        
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.gwt.xml</include>
                </includes>
            </resource>
        </resources>
        
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
            
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.10</version>
                <executions>
                    <execution>
                        <id>default-test</id>
                        <phase/>
                    </execution>
                </executions>
            </plugin>
            
            <!-- GWT -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>${gwt.version}</version>
                <configuration>
                    <strict>true</strict>
                    
                    <testTimeOut>180</testTimeOut>
                    <mode>htmlunit</mode>
                    <includes>**/*GwtTest.java</includes>
                    
                    <logLevel>INFO</logLevel>

                    <copyWebapp>true</copyWebapp>
                    <hostedWebapp>${webappDirectory}</hostedWebapp>

                    <extraJvmArgs>-Xmx1g</extraJvmArgs>
                    <style>${gwt.style}</style>
                    <compileReport>true</compileReport>
                    <compilerMetrics>true</compilerMetrics>

                    <runTarget>index.html</runTarget>
                    <modules>
                        <module>gwt.material.exemple.ReofakeDemo</module>
                    </modules>

                    <!-- mvn gwt:run-codeserver - won't have to use the bookmarklet -->
                    <launcherDir>${project.build.directory}/${project.build.finalName}</launcherDir>
                </configuration>

                <!--Replaced the existing executions block-->
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    
    <repositories>
        <repository>
            <id>oss-sonatype</id>
            <name>oss-sonatype</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
    
    <dependencies>
        <!-- GwtMaterial -->
        <dependency>
            <groupId>com.github.gwtmaterialdesign</groupId>
            <artifactId>gwt-material</artifactId>
            <version>${gwt-material.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.gwtmaterialdesign</groupId>
            <artifactId>gwt-material-themes</artifactId>
            <version>${gwt-material.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.gwtmaterialdesign</groupId>
            <artifactId>gwt-material-addins</artifactId>
            <version>${gwt-material.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.gwtmaterialdesign</groupId>
            <artifactId>gwt-material-table</artifactId>
            <version>${gwt-material-table.version}</version>
        </dependency>

        <!-- GWT -->
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-servlet</artifactId>
            <version>${gwt.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-user</artifactId>
            <version>${gwt.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-codeserver</artifactId>
            <version>${gwt.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-dev</artifactId>
            <version>${gwt.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- GWTP Components -->
        <dependency>
            <groupId>com.gwtplatform</groupId>
            <artifactId>gwtp-mvp-client</artifactId>
            <version>${gwtp.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
```
And I delete all the SNAPSHOT items in my .m2 before test. But the version is still not up to date (Nov 29, 2016) so I edited the overridecss.purple.css file, and I test (deleting the "!important" at line 84).

**Comment by kevzlou7979** [comment]
I just browsed the Themes Repository , here in line 84.
https://github.com/GwtMaterialDesign/gwt-material-themes/blob/release_2.0/src/main/resources/gwt/material/design/themes/purple/css/overridecss.purple.css#L85

I will try to redeploy the themes on Maven.

**Comment by kevzlou7979** [comment]
Check now I have redeployed the snapshot of themes

**Comment by reofake** [comment]
Same result with new snapshot (all windows are blue, and the toolbarColor param is still ignored), but no need to edit the overridecss.purple.css file this time.

**Comment by reofake** [comment]
See https://github.com/GwtMaterialDesign/gwt-material/issues/521 I upload my project.
To reproduce, launch the project, click ToolbarColor, then click the button in bottom right to open the window.

In code (ToolbarView.Java) :
windowEdition.setToolbarColor(Color.GREEN);

**Comment by reofake** [comment]
Is this possible to reopen this issue ? Or should I open a new issue ?

My simple project to reproduce :
[reofake-demo.zip](https://github.com/GwtMaterialDesign/gwt-material/files/670485/reofake-demo.zip)
